[tool.poetry]
name = "colour-science.org"
version = "1.0.0"
description = "Website code for https://www.colour-science.org/"
authors = [ "Colour Developers <colour-science@googlegroups.com>" ]
maintainers = [ "Colour Developers <colour-science@googlegroups.com>" ]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.5"
nikola = { extras = [ "extras" ], version = "^8.*.*" }

flake8 = { version = "*", optional = true }  # Development dependency.
invoke = { version = "*", optional = true }  # Development dependency.
pre-commit = { version = "*", optional = true }  # Development dependency.
yapf = { version = "0.23", optional = true }  # Development dependency.

[tool.poetry.dev-dependencies]
flake8 = "*"
invoke = "*"
pre-commit = "*"
yapf = "0.23"

[tool.poetry.extras]
development = [
    "flake8",
    "invoke",
    "pre-commit",
    "yapf"
]

[build-system]
requires = [ "poetry>=0.12" ]
build-backend = "poetry.masonry.api"
